### PR TITLE
Mocha, Chai, Sinai Unit Tests + Architectural Improvements

### PR DESCRIPTION
**Pull request by phillfarrugia**
This PR addresses issue #2 

As expected writing unit tests often reveals ways to improve architectural decisions in a project. Currently the codebase is not very testable as the Plugins code is tightly coupled with the use of the node-telegram-bot-api module.

- This PR refactors all Plugin related functionality into an external `PluginManager` class, in order to be more reusable, clear, extensible and testable.
- PluginManager is in charge of requiring plugins, loading them, initialising them and safely shutting them down.
- Bot.js becomes nothing more than a bridge between the PluginManager and node-telegram-bot-api. Which is to be expected for now.
- Adds 9 test cases and 4 pending test cases (for handling different message reply types from plugins).

The aim is to setup this project with a free continuous integration server such as Travis CI, to run these tests on each Pull Request and merge. I can do this once this PR has been merged.

### CODE REVIEW

**Comment by crisbal** [comment]
WOW! This is amazing!!!!

I will merge it now. 

Thank you so much for this. This will also be a good way for me to learn about test cases.

What are the next features/things you think we should work on? 

I could for example make a "Common Utilities" module, useful for writing plugins: it will offer basic functions for downloading pages, saving stuff, parsing commands etc.

Thanks again.

**Comment by phillfarrugia** [comment]
Haha! 😜

This is a fun little project, I don't always write javascript but I enjoy fiddling with this.

Sure, checkout my test cases and the frameworks I used. You'll notice tests force you to write more 'testable' code and therefore rethink the ways you write things. Such as separating out any relationships between things.

I reckon we should implement a few great plugins like you've said. Interesting idea for the common utilities module, that would definitely be useful.

I have some ideas to polish the edges of the bot a bit more... if it's okay with you I'll create a bunch of Issues for them so we can discuss and track individually.

**Comment by crisbal** [comment]
Ok, no problem! Open any issue you want.

If I open an issue do you get notified?

**Comment by phillfarrugia** [comment]
@crisbal yep I do, and thanks

**Pull request merged**
